# The name of the action
name: Tests with pytest
# When the action is triggered
on:
  pull_request:
    branches:
      - develop
      - django4

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: volunteer_planner.settings.tests
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.8
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.txt

      # Run pytest
      - name: Test with pytest
        run: pytest -vv
