name: Build, check & tests with pytest

on:
  pull_request:
    branches:
      - develop
      - django4

jobs:
  build-and-test:
    name: Build, check & test
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: volunteer_planner.settings.tests
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.8
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # apt install system dependencies
      - name: Install apt packages
        run: |
          sudo apt install -y gettext

      # Pip install project dependencies
      - name: Install python packages with pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      # Check for missing messages in .po files
      - name: Check for missing messages in .po files
        run: |
          ./makemessages.sh

      # Check for missing Django migrations
      - name: Check for missing Django migrations
        run: python manage.py makemigrations --check

      # Run pytest
      - name: Test with pytest
        run: pytest -vv
