name: Build, check & tests with pytest

on:
  pull_request:
    branches:
      - develop
      - django4

jobs:
  build-and-test:
    name: Build, check & test
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: volunteer_planner.settings.tests
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.8
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      # Check for missing messages in .po files
      - name: Check messages
        run: |
          python manage.py makemessages --all --no-wrap --no-location --no-obsolete
          git diff --ignore-matching-lines=POT-Creation-Date --exit-code

      # Check for missing Django migrations
      - name: Check migrations
        run: python manage.py makemigrations --check

      # Run pytest
      - name: Test /w pytest
        run: pytest -vv
